name: Bug report
description: Report a defect
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Steps, inputs, logs.
    validations:
      required: true
