name: Feature request
description: Propose an enhancement
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
    validations:
      required: true
